### PR TITLE
Adding PERT estimate calculator

### PR DESCRIPTION
**Pull request by jonathanbossenger**
Added PERT estimator for #37 

CSS and JavaScript should probably be separated, but it works as is for now.

### CODE REVIEW

**Comment by vimes1984** [comment]
@spyrosvl we good to merge this?

**Comment by spyrosvl** [comment]
I would prefer it to be a separate file, but whatever :D Merge it please!

**Comment by vimes1984** [comment]
@jonathanbossenger can you seperate this out ?

**Comment by vimes1984** [comment]
@spyrosvl please note the requirement for things to be done in seperate files in the readme :D

**Comment by jonathanbossenger** [comment]
Moved PERT calculator to a separate functions file

**Comment by vimes1984** [comment]
@jonathanbossenger thanks mate :D

**Comment by defunctl** [comment]
This pull request is missing the actual pert-calculator.php file.

**Comment by jonathanbossenger** [comment]
Whoops. @vimes1984 will I have to create a new PR?

**Comment by jin0x** [comment]
@jonathanbossenger Leave it for me mate. I just find out that it was missing and I am almost ready to push :)

**Comment by jin0x** [comment]
PERT Calculator is back as a separate file.

**Comment by jonathanbossenger** [comment]
Sorry chaps, I'm tired, shouldn't be coding tonight.

**Comment by jonathanbossenger** [comment]
Thanks @jin0x

**Comment by jin0x** [comment]
You are welcome @jonathanbossenger 
Maybe you should take some rest :)

**Comment by vimes1984** [comment]
@jonathanbossenger go to sleep mate :D

**Comment by jonathanbossenger** [comment]
Thanks @jin0x @vimes1984 I think I shall do just that ;-)

**Pull request merged**
